# Generated by Django 5.1.2 on 2024-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_model', models.CharField(max_length=120)),
                ('description_model', models.TextField()),
                ('completed_task', models.BooleanField(default=False)),
            ],
        ),
    ]
